const techProducts = [
  {
    name: "Smartphone XYZ",
    price: 699,
    salePrice: 599,
    brand: "Brand A",
    features: ["5G", "128GB Storage", "Triple Camera"],
  },
  {
    name: "Laptop ABC",
    price: 1299,
    salePrice: 1099,
    brand: "Brand B",
    features: ["16GB RAM", "512GB SSD", "Intel i7 Processor"],
  },
  {
    name: "Wireless Earbuds",
    price: 199,
    salePrice: 149,
    brand: "Brand C",
    features: ["Noise Cancelling", "30h Battery Life", "IPX4 Water Resistance"],
  },
  {
    name: "Smartwatch Pro",
    price: 299,
    salePrice: 249,
    brand: "Brand D",
    features: ["Heart Rate Monitor", "GPS", "30+ Sports Modes"],
  },
  {
    name: "Gaming Monitor",
    price: 499,
    salePrice: 399,
    brand: "Brand E",
    features: ["144Hz Refresh Rate", "1ms Response Time", "G-Sync Compatible"],
  },
  {
    name: "Portable SSD",
    price: 129,
    salePrice: 99,
    brand: "Brand F",
    features: ["1TB Capacity", "USB 3.2", "Shock Resistant"],
  },
  {
    name: "Bluetooth Speaker",
    price: 89,
    salePrice: 69,
    brand: "Brand G",
    features: ["10h Playtime", "Water Resistant", "Built-in Microphone"],
  },
  {
    name: "Smart Home Hub",
    price: 199,
    salePrice: 149,
    brand: "Brand H",
    features: ["Voice Control", "Compatible with Alexa", "Home Automation"],
  },
  {
    name: "VR Headset",
    price: 399,
    salePrice: 349,
    brand: "Brand I",
    features: ["6DoF Tracking", "High Resolution", "Wide Field of View"],
  },
  {
    name: "Wireless Charger",
    price: 49,
    salePrice: 39,
    brand: "Brand J",
    features: ["Fast Charging", "Universal Compatibility", "LED Indicator"],
  },
  {
    name: "Action Camera",
    price: 299,
    salePrice: 249,
    brand: "Brand K",
    features: ["4K Video", "Waterproof", "Wide Angle Lens"],
  },
  {
    name: "Laptop Stand",
    price: 39,
    salePrice: 29,
    brand: "Brand L",
    features: ["Adjustable Height", "Foldable", "Cooling Vent"],
  },
  {
    name: "Wireless Mouse",
    price: 49,
    salePrice: 39,
    brand: "Brand M",
    features: ["Ergonomic Design", "USB-C Charging", "Adjustable DPI"],
  },
  {
    name: "Streaming Device",
    price: 49,
    salePrice: 39,
    brand: "Brand N",
    features: ["4K Streaming", "Voice Remote", "Supports Major Apps"],
  },
  {
    name: "Smart Light Bulb",
    price: 15,
    salePrice: 10,
    brand: "Brand O",
    features: ["Color Changing", "App Controlled", "Energy Efficient"],
  },
  {
    name: "USB Hub",
    price: 29,
    salePrice: 19,
    brand: "Brand P",
    features: ["7 Ports", "USB 3.0", "Compact Design"],
  },
  {
    name: "Over-Ear Headphones",
    price: 299,
    salePrice: 249,
    brand: "Brand Q",
    features: ["Active Noise Cancelling", "20h Battery Life", "Comfort Fit"],
  },
  {
    name: "Fitness Tracker",
    price: 99,
    salePrice: 79,
    brand: "Brand R",
    features: ["Step Counter", "Sleep Monitor", "Water Resistant"],
  },
  {
    name: "Webcam",
    price: 89,
    salePrice: 69,
    brand: "Brand S",
    features: ["1080p HD", "Built-in Microphone", "Wide Angle"],
  },
  {
    name: "Network Router",
    price: 149,
    salePrice: 119,
    brand: "Brand T",
    features: ["Wi-Fi 6", "Gigabit Speeds", "Parental Controls"],
  },
];
