const techProducts = [
  {
    name: "Smartphone XYZ",
    price: 699,
    salePrice: 599,
    brand: "Brand A",
    features: ["5G", "128GB Storage", "Triple Camera"],
    img:"https://m.media-amazon.com/images/I/51hvaJzs0RL._AC_UF894,1000_QL80_.jpg"
  },
  {
    name: "Laptop ABC",
    price: 1299,
    salePrice: 1099,
    brand: "Brand B",
    features: ["16GB RAM", "512GB SSD", "Intel i7 Processor"],
    img: "https://cdn-dynmedia-1.microsoft.com/is/image/microsoftcorp/Content-Card-Surface-Laptop-6-Platinum-COMR-M001?wid=834&hei=470&fit=crop",
  },
  {
    name: "Wireless Earbuds",
    price: 199,
    // salePrice: 149,
    brand: "Brand C",
    features: ["Noise Cancelling", "30h Battery Life", "IPX4 Water Resistance"],
    img: "https://m.media-amazon.com/images/I/71exNLc-CnL.jpg",
  },
  {
    name: "Smartwatch Pro",
    price: 299,
    salePrice: 249,
    brand: "Brand D",
    features: ["Heart Rate Monitor", "GPS", "30+ Sports Modes"],
    img: "https://cmf.tech/cdn/shop/files/07__45____03c_2_1200x.png?v=1720164814",
  },
  {
    name: "Gaming Monitor",
    price: 499,
    salePrice: 399,
    brand: "Brand E",
    features: ["144Hz Refresh Rate", "1ms Response Time", "G-Sync Compatible"],
    img: "https://i.dell.com/is/image/DellContent//content/dam/images/products/electronics-and-accessories/dell/monitors/dell-gaming/s3422dwg/s3422dwg-xfp-01-bk.psd?fmt=png-alpha&pscan=auto&scl=1&hei=804&wid=886&qlt=100,1&resMode=sharp2&size=886,804&chrss=full",
  },
  {
    name: "Portable SSD",
    price: 129,
    // salePrice: 99,
    brand: "Brand C",
    features: ["1TB Capacity", "USB 3.2", "Shock Resistant"],
    img: "https://shop.sandisk.com/content/dam/store/en-us/assets/products/portable/extreme-pro-usb-3-1-ssd/gallery/extreme-pro-usb-3-1-ssd-right.png.thumb.319.319.png",
  },
  {
    name: "Bluetooth Speaker",
    price: 89,
    salePrice: 69,
    brand: "Brand A",
    features: ["10h Playtime", "Water Resistant", "Built-in Microphone"],
    img: "https://assets.bosecreative.com/transform/c4f0196c-24ea-4e0f-b3d8-f94035436d8b/SLFLXII_BlueDusk_SF_PDP_Gallery_01?quality=90",
  },
  {
    name: "Smart Home Hub",
    price: 199,
    // salePrice: 149,
    brand: "Brand D",
    features: ["Voice Control", "Compatible with Alexa", "Home Automation"],
    img: "https://aeotec.com/wp-content/uploads/2023/10/SmartHomeHub-s-min.png.webp",
  },
  {
    name: "VR Headset",
    price: 399,
    salePrice: 349,
    brand: "Brand B",
    features: ["6DoF Tracking", "High Resolution", "Wide Field of View"],
    img: "https://webobjects2.cdw.com/is/image/CDW/7352910?$product-main$",
  },
  {
    name: "Wireless Charger",
    price: 49,
    salePrice: 39,
    brand: "Brand E",
    features: ["Fast Charging", "Universal Compatibility", "LED Indicator"],
    img: "https://m.media-amazon.com/images/I/61mBfpz7vKL._AC_UF894,1000_QL80_.jpg",
  },
  {
    name: "Action Camera",
    price: 299,
    // salePrice: 249,
    brand: "Brand A",
    features: ["4K Video", "Waterproof", "Wide Angle Lens"],
    img: "https://media.wired.com/photos/67143780b9b9397e5bf6bc8b/master/w_320%2Cc_limit/GoPro-Hero-13-Black-front-back-Offwhite-Background-SOURCE-Amazon.jpg",
  },
  {
    name: "Laptop Stand",
    price: 39,
    // salePrice: 29,
    brand: "Brand B",
    features: ["Adjustable Height", "Foldable", "Cooling Vent"],
    img: "https://www.nativeunion.com/cdn/shop/files/DeskStand_Black_1800x.png?v=1709025763",
  },
  {
    name: "Wireless Mouse",
    price: 49,
    salePrice: 39,
    brand: "Brand A",
    features: ["Ergonomic Design", "USB-C Charging", "Adjustable DPI"],
    img: "https://us.maxgaming.com/bilder/artiklar/zoom/20125_1.jpg?m=1635949704",
  },
  {
    name: "Streaming Device",
    price: 49,
    salePrice: 39,
    brand: "Brand D",
    features: ["4K Streaming", "Voice Remote", "Supports Major Apps"],
    img: "https://cdn.cs.1worldsync.com/syndication/mediaserverredirect/06b616f143bc6ec1b814aaf8bcb15be3/width(2560).jpg",
  },
  {
    name: "Smart Light Bulb",
    price: 15,
    // salePrice: 10,
    brand: "Brand E",
    features: ["Color Changing", "App Controlled", "Energy Efficient"],
    img: "https://i.pcmag.com/imagery/reviews/02q84k4XLglSVUa6CsA2nWH-5.fit_lim.size_919x518.v1716393293.png",
  },
  {
    name: "USB Hub",
    price: 29,
    salePrice: 19,
    brand: "Brand C",
    features: ["7 Ports", "USB 3.0", "Compact Design"],
    img: "https://webobjects2.cdw.com/is/image/CDW/6840071?$product-main$",
  },
  {
    name: "Over-Ear Headphones",
    price: 299,
    // salePrice: 249,
    brand: "Brand B",
    features: ["Active Noise Cancelling", "20h Battery Life", "Comfort Fit"],
    img: "https://www.joesge.com/cdn/shop/products/Matte_black_studio_2_wireless_x700.png?v=1586883085",
  },
  {
    name: "Fitness Tracker",
    price: 99,
    // salePrice: 79,
    brand: "Brand D",
    features: ["Step Counter", "Sleep Monitor", "Water Resistant"],
    img: "https://m.media-amazon.com/images/I/61dr0pCOsIL._AC_UF894,1000_QL80_.jpg",
  },
  {
    name: "Webcam",
    price: 89,
    salePrice: 69,
    brand: "Brand A",
    features: ["1080p HD", "Built-in Microphone", "Wide Angle"],
    img: "https://i5.walmartimages.com/seo/Webcam-1000-Gooseneck-PC07-Computer-Camera-4-Million-High-Definition-Camera-Usb-Camera-Free-Drive-Light-for-Desktop-Computer-Video-Conferencing_33dd8335-4cfd-4f38-ab03-24de2b9e2f67.ca72b5505ae3349101cc9d8cd2829459.jpeg",
  },
  {
    name: "Network Router",
    price: 149,
    salePrice: 119,
    brand: "Brand E",
    features: ["Wi-Fi 6", "Gigabit Speeds", "Parental Controls"],
    img: "https://www.speedtest.net/s/images/speedtest/about/knowledge/routers/routers/nighthawk-x-10-ad-7200.png",
  },
];

export { techProducts };
